### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by MistGG** [WakBox/Wakxy#1]
This looks similar to the other Wakxy Sniffer, but in  EN.

However, even after changing the dispatch address, it doesn't seem to collect packets.

Does it still work? And can it be used to dupe items?

**Comment by KevinSupertramp** [comment]
Hi there ! I'm not sure, it should work. I'm in holidays right now so i can't check.  I'll let you know in 2 weeks ! Cheers

**Comment by MistGG** [comment]
Cheers! Enjoy your vacation!

**Comment by KevinSupertramp** [comment]
Hi there, i'm back. What's up ? Is it working now ?

**Comment by KevinSupertramp** [comment]
It's all up to date now.
